package com.magicpin.mde.domain.model;

public enum TriggerType {
  NEARBY_SEARCH_DEMAND_SPIKE,
  CONVERSION_DROP,
  LOW_BOOKING_VOLUME,
  REPEAT_INACTIVITY,
  ABANDONED_INTEREST,
  WEEKEND_TRAFFIC_SPIKE,
  COMPETITOR_ACTIVITY,
  CAMPAIGN_INACTIVITY
}

